In [1]:
import cv2
import os
import numpy as np
import json
from utils.augment import DataAugmentForObjectDetection

ModuleNotFoundError: No module named 'skimage'

In [2]:
path = '../datasets/tt100k/test_new'
image_path = os.path.join(path,'3236.jpg')
annotations_path = os.path.join(path,'annotations.json')
image_id = '3236'

In [3]:
annotations = json.loads(open(annotations_path).read())
types = annotations['types']
labels = []
for obj in annotations['imgs'][image_id]['objects']:
    category = obj['category']
    category_id = types.index(category)
    xmin = int(obj['bbox']['xmin'])
    ymin = int(obj['bbox']['ymin'])
    xmax = int(obj['bbox']['xmax'])
    ymax = int(obj['bbox']['ymax'])
    label = [xmin,ymin,xmax,ymax,category_id]
    labels.append(label)
labels = np.array(labels)
print(labels)
print(labels.shape)
bboxes = labels[:,:4].tolist()
print(bboxes)
print(len(bboxes))

[[132 480 167 519  71]
 [170 481 202 515  91]
 [204 481 240 516  22]
 [242 481 278 517 108]
 [687 523 712 556  71]]
(5, 5)
[[132, 480, 167, 519], [170, 481, 202, 515], [204, 481, 240, 516], [242, 481, 278, 517], [687, 523, 712, 556]]
5


In [4]:
img = cv2.imread(image_path)
aug = DataAugmentForObjectDetection()
img_new,bboxes_new = aug.letterbox(img,bboxes)
print(img_new.shape)
print(len(bboxes_new))
print(bboxes_new)

(416, 416, 3)
5
[[128, 136, 138, 147], [139, 137, 148, 146], [149, 137, 159, 147], [159, 137, 170, 147], [286, 149, 293, 158]]


In [6]:
for bbox in bboxes_new:
    x_min = bbox[0]
    y_min = bbox[1]
    x_max = bbox[2]
    y_max = bbox[3]
    draw = cv2.rectangle(img_new,(int(x_min), int(y_min)), (int(x_max), int(y_max)), (0, 255, 0), 1)

In [ ]:
cv2.namedWindow('pic', 0)  # 1表示原图
cv2.moveWindow('pic', 0, 0)
cv2.resizeWindow('pic', 800, 800)  # 可视化的图片大小
cv2.imshow('pic', draw)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
import numpy
import torch
from torch.autograd import Variable

In [12]:
list = []
a = np.array(list)
print(a)

[]


In [13]:
b = Variable(torch.from_numpy(a).type(torch.FloatTensor))
print(b)

tensor([])


In [18]:
print(b.shape)

torch.Size([0])


In [21]:
for t in range(0):
    print(t)